/*
 TABLES
 */
DROP TABLE IF EXISTS "Presence" CASCADE;
DROP TABLE IF EXISTS "Division" CASCADE;
DROP TABLE IF EXISTS "TypeDeMatch" CASCADE;
DROP TABLE IF EXISTS "MatchDeSoccer" CASCADE;
DROP TABLE IF EXISTS "Facture" CASCADE;
DROP TABLE IF EXISTS "Remplace" CASCADE;
DROP TABLE IF EXISTS "Indisponibilite" CASCADE;
DROP TABLE IF EXISTS "Saison" CASCADE;
DROP TABLE IF EXISTS "Equipe" CASCADE;
DROP TABLE IF EXISTS "Joueur" CASCADE;
DROP TABLE IF EXISTS "Membre" CASCADE;
DROP TABLE IF EXISTS "NomSaison" CASCADE;

DROP TABLE IF EXISTS "EquipeHistorique" CASCADE;
DROP TABLE IF EXISTS "JoueurHistorique" CASCADE;
DROP TABLE IF EXISTS "MatchDeSoccerHistorique" CASCADE;

/*
 FUNCTIONS
*/
DROP FUNCTION IF EXISTS "matchDeSoccer_copierOldDansHistorique" CASCADE;
DROP FUNCTION IF EXISTS "matchDeSoccer_beforeUpdate" CASCADE;
DROP FUNCTION IF EXISTS "equipe_copierOldDansHistorique" CASCADE;
DROP FUNCTION IF EXISTS "equipe_beforeUpdate" CASCADE;
DROP FUNCTION IF EXISTS "joueur_copierOldDansHistorique" CASCADE;
DROP FUNCTION IF EXISTS "joueur_beforeUpdate" CASCADE;

/*
 TRIGGERS
*/
DROP TRIGGER IF EXISTS "MatchDeSoccer_beforeUpdate" ON "MatchDeSoccer" CASCADE; 
DROP TRIGGER IF EXISTS "MatchDeSoccer_afterUpdateOrDelete" ON "MatchDeSoccer" CASCADE;
DROP TRIGGER IF EXISTS "Equipe_beforeUpdate" ON "Equipe" CASCADE;
DROP TRIGGER IF EXISTS "Equipe_afterUpdateOrDelete" ON "Equipe" CASCADE;
DROP TRIGGER IF EXISTS "Joueur_beforeUpdate" ON "Joueur" CASCADE;
DROP TRIGGER IF EXISTS "Joueur_afterUpdateOrDelete" ON "Joueur" CASCADE;

/*
 TYPES
 */
DROP TYPE IF EXISTS uint2 CASCADE;
