/*
 TABLES
 */
DROP TABLE IF EXISTS "Presence" CASCADE;
DROP TABLE IF EXISTS "Division" CASCADE;
DROP TABLE IF EXISTS "TypeDeMatch" CASCADE;
DROP TABLE IF EXISTS "MatchDeSoccer" CASCADE;
DROP TABLE IF EXISTS "Facture" CASCADE;
DROP TABLE IF EXISTS "Remplace" CASCADE;
DROP TABLE IF EXISTS "Indisponibilite" CASCADE;
DROP TABLE IF EXISTS "Saison" CASCADE;
DROP TABLE IF EXISTS "Equipe" CASCADE;
DROP TABLE IF EXISTS "Joueur" CASCADE;
DROP TABLE IF EXISTS "Membre" CASCADE;
DROP TABLE IF EXISTS "NomSaison" CASCADE;

/*
 VIEWS
 */
DROP VIEW IF EXISTS "PaiementEquipeFact";
DROP VIEW IF EXISTS "InscriptionFact";
DROP VIEW IF EXISTS "SerieJoueurPresenceFact";
DROP VIEW IF EXISTS "SerieRemplacantPresenceFact";
DROP VIEW IF EXISTS "PresenceFact" CASCADE;
DROP VIEW IF EXISTS "RemplacementFact" CASCADE;
DROP VIEW IF EXISTS "MatchDeSoccerGagnantFact" CASCADE;
DROP VIEW IF EXISTS "MatchDeSoccerPerdantFact" CASCADE;
DROP VIEW IF EXISTS "StatistiqueEquipeFact" CASCADE;
DROP VIEW IF EXISTS "VictoiresJoueurFact" CASCADE;
DROP VIEW IF EXISTS "DefaitesJoueurFact" CASCADE;
DROP VIEW IF EXISTS "StatistiqueJoueurFact" CASCADE;

/*
 TYPES
 */
DROP TYPE IF EXISTS uint2;
